name: Build and Publish Javadocs

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-publish-javadocs:
    permissions:
      contents: write
      pages: write
    uses: qupath/actions/.github/workflows/javadoc.yml@main
    name: Build and upload javadoc
    with:
      java-version: 25
